"""Offline threat rules and defensive patch generation."""

from pathlib import Path
from typing import Any


DATABASE_PORTS = {3306, 5432, 6379, 27017}
ADMIN_PORTS = {21, 22, 3389}


def _open_ports(scan_data: dict[str, Any]) -> list[int]:
    ports: list[int] = []
    for item in scan_data.get("ports", []):
        value = item.get("port") if isinstance(item, dict) else item
        if isinstance(item, dict) and item.get("state") != "open":
            continue
        try:
            ports.append(int(value))
        except (TypeError, ValueError):
            continue
    return sorted(set(ports))


def _missing_headers(scan_data: dict[str, Any]) -> list[str]:
    web = scan_data.get("web", {})
    values = list(web.get("missing_headers", []))
    values.extend(
        header
        for attempt in web.get("attempts", [])
        for header in attempt.get("missing_security_headers", [])
    )
    return sorted({str(value) for value in values if value})


def _server_banner(scan_data: dict[str, Any]) -> str:
    web = scan_data.get("web", {})
    if web.get("server") and web["server"] != "Unknown":
        return str(web["server"])
    for attempt in web.get("attempts", []):
        value = attempt.get("server")
        if value and value != "not disclosed":
            return str(value)
    return "Unknown"


def _generate_patches(scan_data: dict[str, Any], output_dir: Path) -> list[Path]:
    """Write conservative, review-before-use defensive configuration snippets."""
    output_dir.mkdir(parents=True, exist_ok=True)
    ports = _open_ports(scan_data)
    headers = _missing_headers(scan_data)
    header_values = {
        "HSTS": "max-age=31536000; includeSubDomains",
        "CSP": "default-src 'self'; object-src 'none'; frame-ancestors 'none'",
        "X-Frame-Options": "DENY",
        "X-Content-Type-Options": "nosniff",
        "Referrer-Policy": "strict-origin-when-cross-origin",
        "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
        "CORS": "same-origin",
    }
    ufw_lines = [
        "#!/usr/bin/env bash", "set -euo pipefail",
        "# Review these rules before applying them to production.",
    ]
    for port in sorted((DATABASE_PORTS | ADMIN_PORTS) & set(ports)):
        ufw_lines.append(f"sudo ufw deny {port}/tcp")
    if len(ufw_lines) == 3:
        ufw_lines.append("# No administrative or database ports were observed open.")
    htaccess = [
        "# Review for application compatibility before enabling.",
        "<IfModule mod_headers.c>",
    ]
    nginx = ["# Review for application compatibility; place inside the server block."]
    for header in headers:
        value = header_values.get(header)
        if value:
            canonical = {
                "HSTS": "Strict-Transport-Security",
                "CSP": "Content-Security-Policy",
                "CORS": "Access-Control-Allow-Origin",
            }.get(header, header)
            htaccess.append(f'    Header always set {canonical} "{value}"')
            nginx.append(f'    add_header {canonical} "{value}" always;')
    htaccess.append("</IfModule>")
    files = {
        "ufw_rules.sh": "\n".join(ufw_lines) + "\n",
        ".htaccess": "\n".join(htaccess) + "\n",
        "nginx_security.conf": "\n".join(nginx) + "\n",
    }
    paths: list[Path] = []
    for name, content in files.items():
        path = output_dir / name
        path.write_text(content, encoding="utf-8", newline="\n")
        paths.append(path)
    return paths


def analyze_findings(scan_data: dict[str, Any], console: Any = None) -> str:
    """Generate an offline report and defensive patch files."""
    del console
    target = str(scan_data.get("target", "Unknown"))
    ports = _open_ports(scan_data)
    headers = _missing_headers(scan_data)
    tls = scan_data.get("tls", {})
    report = [
        f"# Local Security Threat Report: {target.upper()}",
        "",
        "> **Generated by:** CyberRecon-AI Security Engine | **Developer:** MR ASIF",
        "",
    ]
    report.append("## 1. Offline Vulnerability Correlation")
    if not ports:
        report.append("- **[GOOD]** No common open ports were observed.")
    for port in ports:
        if port in DATABASE_PORTS:
            report.append(f"- **[CRITICAL]** Database/service port {port} is publicly reachable.")
        elif port == 21:
            report.append("- **[HIGH]** FTP is reachable; cleartext credentials and data are possible.")
        elif port in ADMIN_PORTS:
            report.append(f"- **[HIGH]** Administrative service port {port} is reachable.")
        elif port == 80:
            report.append("- **[MEDIUM]** HTTP is reachable; verify HTTPS redirection.")
        elif port == 443:
            report.append("- **[INFO]** HTTPS is reachable.")
        else:
            report.append(f"- **[LOW]** Port {port} is reachable; verify necessity.")
    report.append("\n## 2. Web Security and TLS Findings")
    if headers:
        report.extend(
            f"- **[MEDIUM]** Missing defensive header: `{header}`."
            for header in headers
        )
    else:
        report.append("- **[GOOD]** No missing defensive headers were reported.")
    if tls.get("status") != "ok":
        report.append("- **[REVIEW]** TLS certificate details were unavailable.")
    elif tls.get("weak_or_expiring"):
        report.append(f"- **[HIGH]** TLS certificate expires in {tls.get('days_remaining')} days.")
    banner = _server_banner(scan_data)
    if banner != "Unknown":
        report.append(f"- **[LOW]** Server banner disclosed: `{banner}`.")
    report.extend(
        (
            "\n## 3. Remediation",
            "- Restrict administrative and database services with perimeter and host firewalls.",
            "- Disable FTP where possible and prefer encrypted alternatives.",
            "- Configure missing browser security headers and monitor TLS renewal.",
            "- Review generated configuration snippets before applying them.",
        )
    )
    patch_dir = Path.cwd() / "reports" / "remediation"
    paths = _generate_patches(scan_data, patch_dir)
    report.append("\n## 4. Generated Defensive Artifacts")
    report.extend(f"- `{path}`" for path in paths)
    return "\n".join(report)
