"""Generate reviewable defensive configuration snippets."""

import os
from pathlib import Path
from typing import Any


def _ports(scan_data: dict[str, Any]) -> set[int]:
    return {
        int(item["port"]) for item in scan_data.get("ports", [])
        if item.get("state") == "open" and str(item.get("port", "")).isdigit()
    }


def _headers(scan_data: dict[str, Any]) -> list[str]:
    return sorted(set(scan_data.get("web", {}).get("missing_headers", [])))


def generate_fixes(scan_data: dict[str, Any], output_dir: str | None = None) -> dict[str, Any]:
    """Write UFW, Apache, and Nginx snippets and return their paths."""
    directory = output_dir or os.path.join(os.getcwd(), "reports", "remediation")
    os.makedirs(directory, exist_ok=True)
    headers = _headers(scan_data)
    values = {
        "HSTS": ("Strict-Transport-Security", "max-age=31536000; includeSubDomains"),
        "CSP": ("Content-Security-Policy", "default-src 'self'; object-src 'none'"),
        "X-Frame-Options": ("X-Frame-Options", "DENY"),
        "X-Content-Type-Options": ("X-Content-Type-Options", "nosniff"),
        "Referrer-Policy": ("Referrer-Policy", "strict-origin-when-cross-origin"),
        "Permissions-Policy": ("Permissions-Policy", "camera=(), microphone=(), geolocation=()"),
        "CORS": ("Access-Control-Allow-Origin", "same-origin"),
    }
    blocked = sorted(_ports(scan_data) & {21, 22, 3306, 3389, 5432, 6379, 27017})
    ufw = [
        "#!/usr/bin/env bash",
        "# Author: MR ASIF | Tool: CyberRecon-AI",
        "set -euo pipefail",
        "# Review before applying.",
    ]
    ufw.extend(f"sudo ufw deny {port}/tcp" for port in blocked)
    if not blocked:
        ufw.append("# No administrative, FTP, or database ports were observed open.")
    apache = [
        "# Auto-generated by CyberRecon-AI (MR ASIF)",
        "# Review for compatibility before enabling.",
        "<IfModule mod_headers.c>",
    ]
    nginx = [
        "# Auto-generated by CyberRecon-AI (MR ASIF)",
        "# Review and place inside the appropriate server block.",
    ]
    for header in headers:
        if header in values:
            name, value = values[header]
            apache.append(f'    Header always set {name} "{value}"')
            nginx.append(f'    add_header {name} "{value}" always;')
    apache.append("</IfModule>")
    contents = {
        "ufw_rules.sh": "\n".join(ufw) + "\n",
        ".htaccess": "\n".join(apache) + "\n",
        "nginx_security.conf": "\n".join(nginx) + "\n",
    }
    files = []
    for name, content in contents.items():
        path = Path(os.path.join(directory, name))
        path.write_text(content, encoding="utf-8", newline="\n")
        files.append(str(path))
    return {"directory": directory, "files": files}
